# Generated by Django 4.1.7 on 2023-03-25 20:27

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.events.models.generate_filename
            ),
        ),
    ]
