# Generated by Django 4.1.7 on 2023-04-03 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
