# Generated by Django 4.1.7 on 2023-03-30 18:15

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Загрузите видео для сжатия.",
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="videos/",
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
            },
        ),
    ]
