# Generated by Django 4.1.7 on 2023-03-30 18:32

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={},
        ),
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="uuid",
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(default="TilyaChort", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(
                default="", upload_to=apps.videos.models.compress_video
            ),
            preserve_default=False,
        ),
    ]
