# Generated by Django 4.1.7 on 2023-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео"},
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(max_length=255, upload_to="videos/"),
        ),
    ]
