# Generated by Django 4.1.7 on 2023-03-30 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_options_remove_video_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
    ]
