# Generated by Django 4.1.7 on 2023-04-03 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                (
                    "email",
                    models.EmailField(max_length=219, verbose_name="Электронная почта"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Enter phone number in international format",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="номер телефона",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("Participant", "участник"), ("Viewer", "зритель")],
                        max_length=12,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
