# Generated by Django 4.1.7 on 2023-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                (
                    "email",
                    models.EmailField(max_length=219, verbose_name="Электронная почта"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Enter phone number in international format",
                        max_length=20,
                        unique=True,
                        verbose_name="номер телефона",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("Participant", "участник"), ("Viewer", "зритель")],
                        max_length=12,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
