# Generated by Django 4.1.7 on 2023-03-24 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(max_length=219, verbose_name="Электронная почта"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Enter phone number in international format",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
