# Generated by Django 4.1.7 on 2023-04-03 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reqs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmodel",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                help_text="Enter phone number in international format",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                        regex="^\\(?:[0-9] ?){6,14}[0-9]$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
    ]
