# Generated by Django 4.1.7 on 2023-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reqs", "0002_requestmodel_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmodel",
            name="country",
            field=models.CharField(
                default="Кыргызстан", max_length=255, verbose_name="Страна"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestmodel",
            name="role",
            field=models.CharField(
                choices=[("Participant", "participant"), ("Viewer", "viewer")],
                default="viewer",
                max_length=12,
                verbose_name="Роль",
            ),
            preserve_default=False,
        ),
    ]
