# Generated by Django 4.1.7 on 2023-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reqs", "0002_alter_requestmodel_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmodel",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                help_text="Enter phone number in international format",
                max_length=20,
                unique=True,
                verbose_name="номер телефона",
            ),
        ),
    ]
